
# curl -X 'POST'
#  'http://localhost:8082/api/user/register'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "avatar_url": "https://c-ssl.dtstatic.com/uploads/blog/202302/24/20230224163230_0bc1c.thumb.400_0.jpeg",
#  "user_account": "name.xissg@gmail.com",
#  "user_name": "xissg",
#  "user_password": "LCLSWny20@",
#  "user_role": "admin"
#}'
POST http://localhost:8082/api/user/register
accept: application/json
Content-Type: application/json

{
  "avatar_url": "https://c-ssl.dtstatic.com/uploads/blog/202302/24/20230224163230_0bc1c.thumb.400_0.jpeg",
  "user_account": "name.xissg@gmail.com",
  "user_name": "xissg",
  "user_password": "LCLSWny20@",
  "user_role": "admin"
}

###
# curl -X 'POST'
#  'http://localhost:8082/api/user/login'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "user_account": "name.xissg@gmail.com",
#  "user_password": "LCLSWny20@"
#}'
POST http://localhost:8082/api/user/login
accept: application/json
Content-Type: application/json

{
  "user_account": "name.xissg@gmail.com",
  "user_password": "LCLSWny20@"
}

###

# curl -X 'POST'
#  'http://localhost:8082/api/user/update'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "avatar_url": "string",
#  "user_name": "demo"
#}'
POST http://localhost:8082/api/user/update
accept: application/json
Content-Type: application/json

{
  "user_name": "xissg"
}

###
# curl -X 'POST'
#  'http://localhost:8082/api/user/edit'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "avatar_url": "string",
#  "user_account": "string",
#  "user_name": "string",
#  "user_password": "string",
#  "user_role": "string"
#}'
POST http://localhost:8082/api/user/admin/query
accept: application/json
Content-Type: application/json

{
  "user_name": "xissg"
}

###
# curl -X 'POST'
#  'http://localhost:8082/api/user/admin/query'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "create_time": "string",
#  "id": "string",
#  "is_delete": 0,
#  "user_account": "string",
#  "user_name": "string",
#  "user_role": "string"
#}'
POST http://localhost:8082/api/user/admin/query
accept: application/json
Content-Type: application/json

{

  "is_delete": 0

}

###



###
# curl -X 'GET'
#  'http://localhost:8082/api/user/logout'
#  -H 'accept: application/json'
GET http://localhost:8082/api/user/logout
accept: application/json

###




###
# curl -X 'GET'
#  'http://localhost:8082/api/user/admin/delete'
#  -H 'accept: application/json'
GET http://localhost:8082/api/user/admin/delete/name.xissg@gmail.com
accept: application/json
###
# curl -X 'POST'
#  'http://localhost:8082/api/user/query'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "id": "string",
#  "user_account": "string",
#  "user_name": "string"
#}'







