// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/question/admin/create": {
            "post": {
                "description": "add question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "add question",
                "parameters": [
                    {
                        "description": "add question",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modelquestion.AddQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "add successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "add failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/question/admin/delete": {
            "get": {
                "description": "delete question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "delete question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "delete Question",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delete  successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "delete failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/question/admin/update": {
            "post": {
                "description": "update question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "update question",
                "parameters": [
                    {
                        "description": "update question",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modelquestion.UpdateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "update failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/question/get": {
            "get": {
                "description": "get question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "get question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Get Question",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get question successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/modelquestion.ReturnQuestion"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "EditUserRequest failed\"\t\"get question failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "get questions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "get questions",
                "parameters": [
                    {
                        "description": "Get Questions",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modelquestion.QueryQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get questions successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/modelquestion.ReturnQuestion"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "EditUserRequest failed\"\t\"get questions failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/submit/query": {
            "get": {
                "description": "get question submit result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QuestionSubmit"
                ],
                "summary": "get question submit result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "query  successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/modelquestion.QSReturn"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "query failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "get question submit result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QuestionSubmit"
                ],
                "summary": "get question submit result",
                "parameters": [
                    {
                        "description": "queries",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modelquestion.QueryQuestionSubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "query  successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/modelquestion.QSReturn"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "query failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/submit/submission": {
            "post": {
                "description": "submit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QuestionSubmit"
                ],
                "summary": "submit",
                "parameters": [
                    {
                        "description": "submit code",
                        "name": "modelquestion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modelquestion.AddQuestionSubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "submit success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "submit failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/admin/delete": {
            "get": {
                "description": "DeleteUser user information by user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "DeleteUser user by user account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Useraccount",
                        "name": "user",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DeleteUser successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "DeleteUser failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/admin/query": {
            "post": {
                "description": "Query user list for admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Query user list for admin",
                "parameters": [
                    {
                        "description": "queries",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modeluser.AdminUserQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/modeluser.ReturnAdminUser"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Query failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/admin/update": {
            "post": {
                "description": "admin edit user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "admin edit user information",
                "parameters": [
                    {
                        "description": "User Information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modeluser.EditUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "EditUserRequest successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "EditUserRequest failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "description": "Authenticate user login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User Information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modeluser.LoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Common successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/modeluser.ReturnUser"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Common failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/logout": {
            "get": {
                "description": "User logout",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Logout failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/query": {
            "post": {
                "description": "Get user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Query user",
                "parameters": [
                    {
                        "description": "queries",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modeluser.UserQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/modeluser.ReturnUser"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Query failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User register",
                "parameters": [
                    {
                        "description": "User Information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modeluser.AddUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success registered",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Register failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/update": {
            "post": {
                "description": "Update user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User update",
                "parameters": [
                    {
                        "description": "User Information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modeluser.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "UpdateUserRequest successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "UpdateUserRequest failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "modelquestion.AddQuestionRequest": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "answer": {
                    "description": "\"题目答案\"",
                    "type": "string"
                },
                "content": {
                    "description": "\"内容\"",
                    "type": "string"
                },
                "judge_case": {
                    "description": "\"判题用例json数组\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/modelquestion.JudgeCase"
                    }
                },
                "judge_config": {
                    "description": "\"判题配置json对象\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/modelquestion.JudgeConfig"
                        }
                    ]
                },
                "tags": {
                    "description": "\"标签列表json数组\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/modelquestion.Tags"
                    }
                },
                "title": {
                    "description": "\"标题\"",
                    "type": "string"
                },
                "user_id": {
                    "description": "\"创建用户id\"",
                    "type": "string"
                }
            }
        },
        "modelquestion.AddQuestionSubmitRequest": {
            "type": "object",
            "required": [
                "question_id"
            ],
            "properties": {
                "code": {
                    "description": "\"用户代码\"",
                    "type": "string"
                },
                "language": {
                    "description": "\"编程语言\"",
                    "type": "string"
                },
                "question_id": {
                    "description": "\"题目id\"",
                    "type": "string"
                }
            }
        },
        "modelquestion.JudgeCase": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                }
            }
        },
        "modelquestion.JudgeConfig": {
            "type": "object",
            "required": [
                "memory_limit",
                "stack_limit",
                "time_limit"
            ],
            "properties": {
                "memory_limit": {
                    "type": "integer"
                },
                "stack_limit": {
                    "type": "integer"
                },
                "time_limit": {
                    "type": "integer"
                }
            }
        },
        "modelquestion.JudgeInfo": {
            "type": "object",
            "properties": {
                "memory": {
                    "description": "单位为kb",
                    "type": "integer"
                },
                "message": {
                    "description": "值为以上枚举值",
                    "type": "string"
                },
                "time": {
                    "description": "单位为ms",
                    "type": "integer"
                }
            }
        },
        "modelquestion.QSReturn": {
            "type": "object",
            "properties": {
                "judge_info": {
                    "description": "\"判题信息json对象(包含上面的枚举值)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/modelquestion.JudgeInfo"
                        }
                    ]
                },
                "language": {
                    "description": "\"编程语言\"",
                    "type": "string"
                },
                "question_id": {
                    "description": "题目id",
                    "type": "string"
                },
                "status": {
                    "description": "\"判题状态（0-待判题,1-判题中,2-成功,3-失败)\",",
                    "type": "integer"
                }
            }
        },
        "modelquestion.QueryQuestionRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "\"内容\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "judge_case": {
                    "description": "\"判题用例json数组\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/modelquestion.JudgeCase"
                    }
                },
                "tags": {
                    "description": "\"标签列表json数组\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/modelquestion.Tags"
                    }
                },
                "title": {
                    "description": "\"标题\"",
                    "type": "string"
                },
                "user_id": {
                    "description": "\"创建用户id\"",
                    "type": "string"
                }
            }
        },
        "modelquestion.QueryQuestionSubmitRequest": {
            "type": "object",
            "properties": {
                "language": {
                    "description": "\"编程语言\"",
                    "type": "string"
                },
                "question_id": {
                    "description": "\"判题id\"",
                    "type": "string"
                },
                "status": {
                    "description": "\"判题状态（0-待判题,1-判题中,2-成功,3-失败)\",",
                    "type": "integer"
                },
                "user_id": {
                    "description": "\"创建用户id\"",
                    "type": "string"
                }
            }
        },
        "modelquestion.ReturnQuestion": {
            "type": "object",
            "properties": {
                "accept_num": {
                    "description": "\"题目通过数\"",
                    "type": "integer"
                },
                "content": {
                    "description": "\"内容\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "judge_config": {
                    "description": "\"判题配置json对象\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/modelquestion.JudgeConfig"
                        }
                    ]
                },
                "submit_num": {
                    "description": "\"题目提交数",
                    "type": "integer"
                },
                "tags": {
                    "description": "\"标签列表json数组\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/modelquestion.Tags"
                    }
                },
                "thum_num": {
                    "description": "\"点赞数\"",
                    "type": "integer"
                },
                "title": {
                    "description": "\"标题\"",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "string"
                }
            }
        },
        "modelquestion.Tags": {
            "type": "object",
            "properties": {
                "easy": {
                    "type": "string"
                },
                "hard": {
                    "type": "string"
                },
                "medium": {
                    "type": "string"
                }
            }
        },
        "modelquestion.UpdateQuestionRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "answer": {
                    "description": "\"题目答案\"",
                    "type": "string"
                },
                "content": {
                    "description": "\"内容\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "judge_case": {
                    "description": "\"判题用例json数组\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/modelquestion.JudgeCase"
                    }
                },
                "judge_config": {
                    "description": "\"判题配置json对象\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/modelquestion.JudgeConfig"
                        }
                    ]
                },
                "tags": {
                    "description": "\"标签列表json数组\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/modelquestion.Tags"
                    }
                },
                "title": {
                    "description": "\"标题\"",
                    "type": "string"
                }
            }
        },
        "modeluser.AddUserRequest": {
            "type": "object",
            "required": [
                "user_account",
                "user_password"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "user_account": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "user_name": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 7
                }
            }
        },
        "modeluser.AdminUserQueryRequest": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "is_delete": {
                    "description": "是否删除",
                    "type": "integer"
                },
                "user_account": {
                    "description": "用户账号",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "user_role": {
                    "description": "匿名用户，普通用户，管理员，禁用用户",
                    "type": "string"
                }
            }
        },
        "modeluser.EditUserRequest": {
            "type": "object",
            "required": [
                "user_account"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "user_account": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string"
                },
                "user_role": {
                    "type": "string"
                }
            }
        },
        "modeluser.LoginUserRequest": {
            "type": "object",
            "required": [
                "user_account",
                "user_password"
            ],
            "properties": {
                "user_account": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "user_password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 7
                }
            }
        },
        "modeluser.ReturnAdminUser": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "user_account": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_role": {
                    "type": "string"
                }
            }
        },
        "modeluser.ReturnUser": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "user_account": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "modeluser.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 7
                }
            }
        },
        "modeluser.UserQueryRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "user_account": {
                    "description": "用户账号",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户昵称",
                    "type": "string"
                }
            }
        },
        "utils.ApiResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "用户管理系统",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
