// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/question/admin/add": {
            "post": {
                "description": "Add question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Add question",
                "parameters": [
                    {
                        "description": "Add question",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_question.AddQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Add question success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Add  question fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/question/admin/delete": {
            "get": {
                "description": "Delete question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Delete question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Question id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete  success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Delete fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/question/admin/update": {
            "post": {
                "description": "Update question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Update question",
                "parameters": [
                    {
                        "description": "Update condition",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_question.UpdateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Update fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/question/query": {
            "get": {
                "description": "Query question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Query question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Question id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query question success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model_question.ReturnQuestion"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Query question fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Get question list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Get question list",
                "parameters": [
                    {
                        "description": "Query conditions",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_question.QueryQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get question list success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model_question.ReturnQuestion"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Get question list failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/submit/add": {
            "post": {
                "description": "Submit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QuestionSubmit"
                ],
                "summary": "Submit",
                "parameters": [
                    {
                        "description": "Submit code",
                        "name": "model_question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_question.AddQuestionSubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submit success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Submit failed",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/submit/query": {
            "get": {
                "description": "Get question submit result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QuestionSubmit"
                ],
                "summary": "Get question submit result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Query id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query  success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model_question.ReturnQS"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Query fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Get question submit list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QuestionSubmit"
                ],
                "summary": "Get question submit list",
                "parameters": [
                    {
                        "description": "Query condition",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_question.QueryQuestionSubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query  success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model_question.ReturnQS"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Query fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/admin/delete": {
            "get": {
                "description": "DeleteUser user  by user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "DeleteUser user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User account",
                        "name": "user",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete user success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Delete user fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/admin/query": {
            "post": {
                "description": "Query user list for admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Admin query",
                "parameters": [
                    {
                        "description": "queries",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_user.AdminUserQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model_user.ReturnAdminUser"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Query fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/admin/update": {
            "post": {
                "description": "Admin edit user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Admin edit user information",
                "parameters": [
                    {
                        "description": "User information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_user.EditUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Edit user request success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Edit user request fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "description": "User login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "User information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_user.LoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model_user.ReturnUser"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Login fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/logout": {
            "get": {
                "description": "User logout",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "Logout success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Logout fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/query": {
            "post": {
                "description": "Query user list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Query user",
                "parameters": [
                    {
                        "description": "Query",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_user.UserQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model_user.ReturnUser"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Query fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "User information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_user.AddUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Register success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Register fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/update": {
            "post": {
                "description": "Update user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "description": "Update information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model_user.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update user request success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Update user request fail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api_response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api_response.ApiResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "model_question.AddQuestionRequest": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "\"题目答案\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "content": {
                    "description": "\"内容\"",
                    "type": "string"
                },
                "judge_case": {
                    "description": "\"判题用例json数组\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model_question.JudgeCase"
                    }
                },
                "judge_config": {
                    "description": "\"判题配置json对象\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model_question.JudgeConfig"
                        }
                    ]
                },
                "tag": {
                    "description": "\"标签列表json数组\"",
                    "type": "string"
                },
                "title": {
                    "description": "\"标题\"",
                    "type": "string"
                },
                "user_id": {
                    "description": "\"创建用户id\"",
                    "type": "string"
                }
            }
        },
        "model_question.AddQuestionSubmitRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"用户代码\"",
                    "type": "string"
                },
                "language": {
                    "description": "\"编程语言\"",
                    "type": "string"
                },
                "question_id": {
                    "description": "\"题目id\"",
                    "type": "string"
                }
            }
        },
        "model_question.JudgeCase": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                }
            }
        },
        "model_question.JudgeConfig": {
            "type": "object",
            "properties": {
                "memory_limit": {
                    "type": "integer"
                },
                "time_limit": {
                    "type": "integer"
                }
            }
        },
        "model_question.JudgeInfo": {
            "type": "object",
            "properties": {
                "memory": {
                    "description": "单位为kb",
                    "type": "integer"
                },
                "message": {
                    "description": "值为以上枚举值",
                    "type": "string"
                },
                "time": {
                    "description": "单位为ms",
                    "type": "integer"
                }
            }
        },
        "model_question.QueryQuestionRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "\"内容\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "tag": {
                    "description": "\"标签列表json数组\"",
                    "type": "string"
                },
                "title": {
                    "description": "\"标题\"",
                    "type": "string"
                },
                "user_id": {
                    "description": "\"创建用户id\"",
                    "type": "string"
                }
            }
        },
        "model_question.QueryQuestionSubmitRequest": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "\"答案\"",
                    "type": "string"
                },
                "language": {
                    "description": "\"编程语言\"",
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "question_id": {
                    "description": "\"判题id\"",
                    "type": "string"
                },
                "status": {
                    "description": "\"判题状态（0-待判题,1-判题中,2-成功,3-失败)\",",
                    "type": "integer"
                },
                "user_id": {
                    "description": "\"创建用户id\"",
                    "type": "string"
                }
            }
        },
        "model_question.ReturnQS": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "\"答案\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "judge_info": {
                    "description": "\"判题信息json对象(包含上面的枚举值)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model_question.JudgeInfo"
                    }
                },
                "language": {
                    "description": "\"编程语言\"",
                    "type": "string"
                },
                "question_id": {
                    "description": "题目id",
                    "type": "string"
                },
                "status": {
                    "description": "\"判题状态（0-待判题,1-判题中,2-成功,3-失败)\",",
                    "type": "integer"
                }
            }
        },
        "model_question.ReturnQuestion": {
            "type": "object",
            "properties": {
                "accept_num": {
                    "description": "\"题目通过数\"",
                    "type": "integer"
                },
                "answer": {
                    "description": "\"题目答案\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "content": {
                    "description": "\"内容\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "judge_config": {
                    "description": "\"判题配置json对象\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model_question.JudgeConfig"
                        }
                    ]
                },
                "submit_num": {
                    "description": "\"题目提交数",
                    "type": "integer"
                },
                "tag": {
                    "description": "\"标签列表json数组\"",
                    "type": "string"
                },
                "thum_num": {
                    "description": "\"点赞数\"",
                    "type": "integer"
                },
                "title": {
                    "description": "\"标题\"",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "string"
                }
            }
        },
        "model_question.UpdateQuestionRequest": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "\"题目答案\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "content": {
                    "description": "\"内容\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "judge_case": {
                    "description": "\"判题用例json数组\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model_question.JudgeCase"
                    }
                },
                "judge_config": {
                    "description": "\"判题配置json对象\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model_question.JudgeConfig"
                        }
                    ]
                },
                "tag": {
                    "description": "\"标签列表json数组\"",
                    "type": "string"
                },
                "title": {
                    "description": "\"标题\"",
                    "type": "string"
                }
            }
        },
        "model_user.AddUserRequest": {
            "type": "object",
            "required": [
                "user_account",
                "user_password"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "user_account": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "user_name": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 7
                }
            }
        },
        "model_user.AdminUserQueryRequest": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "is_delete": {
                    "description": "是否删除",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "user_account": {
                    "description": "用户账号",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "user_role": {
                    "description": "匿名用户，普通用户，管理员，禁用用户",
                    "type": "string"
                }
            }
        },
        "model_user.EditUserRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "user_account": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string"
                },
                "user_role": {
                    "type": "string"
                }
            }
        },
        "model_user.LoginUserRequest": {
            "type": "object",
            "properties": {
                "user_account": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string"
                }
            }
        },
        "model_user.ReturnAdminUser": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "user_account": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_role": {
                    "type": "string"
                }
            }
        },
        "model_user.ReturnUser": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "user_account": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "model_user.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string"
                }
            }
        },
        "model_user.UserQueryRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "page": {
                    "description": "查询页号",
                    "type": "integer"
                },
                "page_size": {
                    "description": "查询页大小",
                    "type": "integer"
                },
                "user_account": {
                    "description": "用户账号",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户昵称",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "用户管理系统",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
