definitions:
  model.ApiResponse:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.ResultUser:
    properties:
      avatar_url:
        description: 用户头像
        type: string
      create_time:
        description: 创建时间
        type: string
      id:
        description: id
        type: integer
      user_account:
        description: 用户账号
        type: string
      user_name:
        description: 用户昵称
        type: string
      user_role:
        description: 0为普通用户, 1为会员用户
        type: integer
    type: object
info:
  contact: {}
  title: 用户管理系统
  version: "0.1"
paths:
  /user/admin/delete:
    get:
      consumes:
      - application/json
      description: Delete user information by username
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Delete successful
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Delete failed
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Delete user by username
      tags:
      - User
  /user/admin/query:
    get:
      consumes:
      - application/json
      description: Get user information by username
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Query successful
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ResultUser'
              type: object
        "400":
          description: Query failed
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Query user by username
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: Authenticate user login
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ResultUser'
              type: object
        "400":
          description: Login failed
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: User login
      tags:
      - User
  /user/logout:
    get:
      consumes:
      - application/json
      description: User logout
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Logout successful
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Logout failed
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: User logout
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success registered
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ResultUser'
              type: object
        "400":
          description: Registration failed
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: User registration
      tags:
      - User
  /user/update:
    post:
      consumes:
      - application/json
      description: Update user information
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Update successful
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Update failed
          schema:
            allOf:
            - $ref: '#/definitions/model.ApiResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: User update
      tags:
      - User
swagger: "2.0"
